### ISSUE TITLE
Passing function to Column `sort_by` results in an error

### ISSUE THREAD

**Issue by hadfieldn** [surface-ui/surface_bulma#18]
I have a Table with a date column and I'm trying to use the `sort_by` prop described in the [documentation for Column](https://github.com/surface-ui/surface_bulma/blob/master/lib/surface_bulma/table/column.ex#L41):

```mustache
  <Column label="Date" sort_by={{ {fn i -> Map.get(i, :datefield) end, &Date.compare/2} }}>
    {{ formatted_date(row.inserted_at) }}
  </Column>
```

This results in the following error:
```
invalid value for attribute "phx-value-value". Expected a type that implements the String.Chars protocol (e.g. string, boolean, integer, atom, ...), got: {#Function<1.56407787/1 in MyAppWeb.Live.Components.Table.render/1>, &Date.compare/2}
```

I'm thinking the problem happens when `SurfaceBulma.Table` [passes `col.sort_by` as the `phx-value-value` prop](https://github.com/surface-ui/surface_bulma/blob/master/lib/surface_bulma/table.ex#L70) for the anchor tag for `sorted_click` events, since `phx-value-value` appears to need a string but is getting the tuple instead?

Or am I doing something wrong? I'm pretty new to both Surface and LiveView. Thanks in advance!

**Comment by Zurga** [comment]
Pull request: #21 should fix this, I was experiencing the same issue.

**Comment by Zurga** [comment]
I am closing this because #21  fixed this.
