### ISSUE TITLE
Issues combining <Form> and <Modal.Card>

### ISSUE THREAD

**Issue by thorsten-de** [surface-ui/surface_bulma#24]
At the moment, I am implementing some edit forms to use `Modal.Card`, like this one:

![modal-form](https://user-images.githubusercontent.com/781602/129047790-9f9423bc-51bd-4dd1-89c2-73cef03b5b8e.png)

Before the last update, I had implemented a `Modal.Card` myself, which I got rid of now because it had a similar design. It looks reasonably well, but there are some minor issues:

- the **header title** is shown only if close button is shown
- the **close button** interferes with my form and _triggers a form submit_. Perhaps setting type="button" on the close button could prevent that
- (optional) closing on `ESC`-Button or clicking the background would be nice
- it feels a bit ugly to wrap the whole `Card` component into the `Form` (see below), but I want to show the form submit button inside the modal footer. 

### Structure
```html
<Form ...>
  <Card ...>
    <Header>Title</Header>
      ...some form fields....
    <Footer>
      <Form.Submit .../>
      <Button ...>Cancel</Button>
    </Footer>
  </Card>
</Form>
```

**Comment by Zurga** [comment]
Thanks for the submission of the issue, sorry for the late reply. The things you propose are all good things to change in the Modal.Card component. I had noticed this problem with the modal buttons before as well. Maybe just using a `<a>` tag styled as a button would also be an option.

I was working on some other stuff in master and decided to fix what you described. I'll update when i pushed. Can you test it then?

If you have any other issues, don't hesitate to submit an issue and/or pull request with a possible fix.

**Comment by Zurga** [comment]
@thorsten-de, I will close this due to the issue being fixed, by testing it myself.
