### ISSUE TITLE
Will it work with Surface 0.7.0?

### ISSUE THREAD

**Issue by jinxter555** [surface-ui/surface_bulma#27]
mix test test/bulma_test/surface_bulma/form_test.exs 

  1) test form as an atom (SurfaceBulma.Components.FormTest)
     test/bulma_test/surface_bulma/form_test.exs:37
     ** (RuntimeError) invalid value for property "errors". Expected a :keyword, got: nil.

I am looking forward to use surface bulma on a project.

**Comment by Zurga** [comment]
Thanks for the issue. The tests are not all passing, due to a large amount of components that were added. I will have a look to see if 0.7.0 is working but it seems like it should. If you want to help this project by fixing some tests, that would be very much appreciated!

**Comment by Zurga** [comment]
My assumption was wrong, this is a bug in SurfaceBulma.Component. It has been fixed and will be published in 0.3.2. I will update the `master` branch to use Surface 0.7 and publish that as version 0.4.0. It will have the fix for the form errors assign.
