### ISSUE TITLE
`class` prop seems to be required in `<Title/>`

### ISSUE THREAD

**Issue by c4lliope** [surface-ui/surface_bulma#31]
Some chosen `deps`:
```ex
[     {:phoenix, "~> 1.7.7"},
      {:phoenix_ecto, "~> 4.4"},
      {:phoenix_html, "~> 3.3"},
      {:phoenix_live_dashboard, "~> 0.7.0"},
      {:phoenix_live_reload, "~> 1.2", only: :dev},
      {:phoenix_live_view, "~> 0.18.18"},
      {:surface, "~> 0.10.0"},
      {:surface_bulma, github: "surface-ui/surface_bulma"},
    # ...
]
```

Minimal reproduction:

```ex
defmodule PainWeb.Order do
  use PainWeb, :surface_live_view

  alias SurfaceBulma.Title

  def render(assigns) do
    ~F"""
      <Title size="3" class="" >Schedule an appointment</Title>
    """
  end
end
```

...renders:

![image](https://github.com/surface-ui/surface_bulma/assets/30454698/ca17d082-abac-4c55-9cdc-205d02293018)

```ex
defmodule PainWeb.Order do
  use PainWeb, :surface_live_view

  alias SurfaceBulma.Title

  def render(assigns) do
    ~F"""
      <Title size="3">Schedule an appointment</Title>
    """
  end
end
```

...errors:

- - -

# ArgumentError at GET /order

Exception:

    ** (ArgumentError) argument error
        :erlang.++(["title", "is-3", {:"is-spaced", nil} | nil], [])
        (surface 0.10.0) lib/surface/type_handler/css_class.ex:35: Surface.TypeHandler.CssClass.expr_to_value/3
        (surface 0.10.0) lib/surface/type_handler.ex:150: Surface.TypeHandler.expr_to_value!/7
        (surface_bulma 0.4.0) lib/surface_bulma/title.ex:18: anonymous fn/2 in SurfaceBulma.Title."render (overridable 1)"/1
        (phoenix_live_view 0.18.18) lib/phoenix_live_view/diff.ex:398: Phoenix.LiveView.Diff.traverse/7
        (phoenix_live_view 0.18.18) lib/phoenix_live_view/diff.ex:544: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/7
        (elixir 1.15.4) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
        (phoenix_live_view 0.18.18) lib/phoenix_live_view/diff.ex:396: Phoenix.LiveView.Diff.traverse/7
        (phoenix_live_view 0.18.18) lib/phoenix_live_view/diff.ex:544: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/7
        (elixir 1.15.4) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
        (phoenix_live_view 0.18.18) lib/phoenix_live_view/diff.ex:396: Phoenix.LiveView.Diff.traverse/7
        (phoenix_live_view 0.18.18) lib/phoenix_live_view/diff.ex:544: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/7
        (elixir 1.15.4) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
        (phoenix_live_view 0.18.18) lib/phoenix_live_view/diff.ex:396: Phoenix.LiveView.Diff.traverse/7
        (phoenix_live_view 0.18.18) lib/phoenix_live_view/diff.ex:139: Phoenix.LiveView.Diff.render/3
        (phoenix_live_view 0.18.18) lib/phoenix_live_view/static.ex:252: Phoenix.LiveView.Static.to_rendered_content_tag/4
        (phoenix_live_view 0.18.18) lib/phoenix_live_view/static.ex:135: Phoenix.LiveView.Static.render/3
        (phoenix_live_view 0.18.18) lib/phoenix_live_view/controller.ex:39: Phoenix.LiveView.Controller.live_render/3
        (phoenix 1.7.7) lib/phoenix/router.ex:430: Phoenix.Router.__call__/5
        (pain 0.1.0) lib/pain_web/endpoint.ex:1: PainWeb.Endpoint.plug_builder_call/2
    

Code:

`nofile`

    No code available.

  Called with 2 arguments

  * `["title", "is-3", {:"is-spaced", nil} | nil]`
  * `[]`
  
`lib/surface/type_handler/css_class.ex`

    30       expr_to_value(value, opts, ctx)
    31     end
    32   
    33     def expr_to_value(clauses, opts, ctx) do
    34       value =
    35>        Enum.reduce(clauses ++ opts, [], fn item, classes ->
    36           case item do
    37             list when is_list(list) ->
    38               case expr_to_value(list, [], ctx) do
    39                 {:ok, new_classes} -> Enum.reverse(new_classes) ++ classes
    40                 error -> error
    
`lib/surface/type_handler.ex`

    145           IOHelper.compile_error(message, meta.file, meta.line)
    146       end
    147     end
    148   
    149     def expr_to_value!(type, name, clauses, opts, module, original, ctx) do
    150>      case handler(type).expr_to_value(clauses, opts, ctx) do
    151         {:ok, value} ->
    152           value
    153   
    154         {:error, value} ->
    155           message = runtime_error_message(type, name, value, module, original)
    
`lib/surface_bulma/title.ex`

    13     prop spaced, :boolean
    14   
    15     slot default
    16   
    17     def render(assigns) do
    18>      ~F"""
    19       <h1 :if={@size == "1"} class={["title", "is-1", "is-spaced": @spaced] ++ @class}><#slot /></h1>
    20       <h2 :if={@size == "2"} class={["title", "is-2", "is-spaced": @spaced] ++ @class}><#slot /></h2>
    21       <h3 :if={@size == "3"} class={["title", "is-3", "is-spaced": @spaced] ++ @class}><#slot /></h3>
    22       <h4 :if={@size == "4"} class={["title", "is-4", "is-spaced": @spaced] ++ @class}><#slot /></h4>
    23       <h5 :if={@size == "5"} class={["title", "is-5", "is-spaced": @spaced] ++ @class}><#slot /></h5>
    
`lib/phoenix_live_view/diff.ex`

    393            changed?
    394          ) do
    395       {_counter, diff, children, pending, components, template} =
    396         traverse_dynamic(
    397           socket,
    398>          invoke_dynamic(rendered, false),
    399           %{},
    400           pending,
    401           components,
    402           template,
    403           changed?
    
`lib/phoenix_live_view/diff.ex`

    539       Enum.reduce(dynamic, {0, %{}, children, pending, components, template}, fn
    540         entry, {counter, diff, children, pending, components, template} ->
    541           child = Map.get(children, counter)
    542   
    543           {serialized, child_fingerprint, pending, components, template} =
    544>            traverse(socket, entry, child, pending, components, template, changed?)
    545   
    546           # If serialized is nil, it means no changes.
    547           # If it is an empty map, then it means it is a rendered struct
    548           # that did not change, so we don't have to emit it either.
    549           diff =
    
`lib/enum.ex`

    No code available.

`lib/phoenix_live_view/diff.ex`

    391            components,
    392            template,
    393            changed?
    394          ) do
    395       {_counter, diff, children, pending, components, template} =
    396>        traverse_dynamic(
    397           socket,
    398           invoke_dynamic(rendered, false),
    399           %{},
    400           pending,
    401           components,
    
`lib/phoenix_live_view/diff.ex`

    539       Enum.reduce(dynamic, {0, %{}, children, pending, components, template}, fn
    540         entry, {counter, diff, children, pending, components, template} ->
    541           child = Map.get(children, counter)
    542   
    543           {serialized, child_fingerprint, pending, components, template} =
    544>            traverse(socket, entry, child, pending, components, template, changed?)
    545   
    546           # If serialized is nil, it means no changes.
    547           # If it is an empty map, then it means it is a rendered struct
    548           # that did not change, so we don't have to emit it either.
    549           diff =
    
`lib/enum.ex`

    No code available.

`lib/phoenix_live_view/diff.ex`

    391            components,
    392            template,
    393            changed?
    394          ) do
    395       {_counter, diff, children, pending, components, template} =
    396>        traverse_dynamic(
    397           socket,
    398           invoke_dynamic(rendered, false),
    399           %{},
    400           pending,
    401           components,
    
`lib/phoenix_live_view/diff.ex`

    539       Enum.reduce(dynamic, {0, %{}, children, pending, components, template}, fn
    540         entry, {counter, diff, children, pending, components, template} ->
    541           child = Map.get(children, counter)
    542   
    543           {serialized, child_fingerprint, pending, components, template} =
    544>            traverse(socket, entry, child, pending, components, template, changed?)
    545   
    546           # If serialized is nil, it means no changes.
    547           # If it is an empty map, then it means it is a rendered struct
    548           # that did not change, so we don't have to emit it either.
    549           diff =
    
`lib/enum.ex`

    No code available.

`lib/phoenix_live_view/diff.ex`

    391            components,
    392            template,
    393            changed?
    394          ) do
    395       {_counter, diff, children, pending, components, template} =
    396>        traverse_dynamic(
    397           socket,
    398           invoke_dynamic(rendered, false),
    399           %{},
    400           pending,
    401           components,
    
`lib/phoenix_live_view/diff.ex`

    134       render(%{socket | fingerprints: new_fingerprints()}, rendered, new_components(uuids))
    135     end
    136   
    137     def render(%{fingerprints: prints} = socket, %Rendered{} = rendered, components) do
    138       {diff, prints, pending, components, nil} =
    139>        traverse(socket, rendered, prints, %{}, components, nil, true)
    140   
    141       # cid_to_component is used by maybe_reuse_static and it must be a copy before changes.
    142       # However, given traverse does not change cid_to_component, we can read it now.
    143       {cid_to_component, _, _} = components
    144   
    
`lib/phoenix_live_view/static.ex`

    247       Phoenix.HTML.Tag.content_tag(tag, "", attrs)
    248     end
    249   
    250     defp to_rendered_content_tag(socket, tag, view, attrs) do
    251       rendered = Utils.to_rendered(socket, view)
    252>      {_, diff, _} = Diff.render(socket, rendered, Diff.new_components())
    253       Phoenix.HTML.Tag.content_tag(tag, {:safe, Diff.to_iodata(diff)}, attrs)
    254     end
    255   
    256     defp load_live!(view_or_component, kind) do
    257       case view_or_component.__live__() do
    
`lib/phoenix_live_view/static.ex`

    130             {:data, data_attrs}
    131             | extended_attrs
    132           ]
    133   
    134           try do
    135>            {:ok, to_rendered_content_tag(socket, tag, view, attrs), socket.assigns}
    136           catch
    137             :throw, {:phoenix, :child_redirect, redirected, flash} ->
    138               {:stop, Utils.replace_flash(%{socket | redirected: redirected}, flash)}
    139           end
    140   
    
`lib/phoenix_live_view/controller.ex`

    34           end
    35         end
    36   
    37     """
    38     def live_render(%Plug.Conn{} = conn, view, opts \\ []) do
    39>      case LiveView.Static.render(conn, view, opts) do
    40         {:ok, content, socket_assigns} ->
    41           conn
    42           |> Phoenix.Controller.put_view(LiveView.Static)
    43           |> Phoenix.Controller.render(
    44             "template.html",
    
`lib/phoenix/router.ex`

    425           :telemetry.execute([:phoenix, :router_dispatch, :stop], measurements, metadata)
    426           halted_conn
    427   
    428         %Plug.Conn{} = piped_conn ->
    429           try do
    430>            plug.call(piped_conn, plug.init(opts))
    431           else
    432             conn ->
    433               measurements = %{duration: System.monotonic_time() - start}
    434               metadata = %{metadata | conn: conn}
    435               :telemetry.execute([:phoenix, :router_dispatch, :stop], measurements, metadata)
    
`lib/pain_web/endpoint.ex`

    1>  defmodule PainWeb.Endpoint do
    2     use Phoenix.Endpoint, otp_app: :pain
    3   
    4     # The session will be stored in the cookie and signed,
    5     # this means its contents can be read but not tampered with.
    6     # Set :encryption_salt if you would also like to encrypt it.
    

### Params

    %{}

### Request info

  * URI: http://0.0.0.0:4000/order
  * Query string: 

### Headers
  
  * accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
  * accept-encoding: gzip, deflate
  * accept-language: en-US,en;q=0.5
  * connection: keep-alive
  * cookie: _pain_key=SFMyNTY.g3QAAAABbQAAAAtfY3NyZl90b2tlbm0AAAAYQjZ3YURjTW9BZEtTMGk3YXJBeHVoVzlw.pvZkj7mPLmIkzMPehthaOXA0Sd10k9BEeo7YU6xaJKY
  * dnt: 1
  * host: 0.0.0.0:4000
  * upgrade-insecure-requests: 1
  * user-agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0

### Session

    %{"_csrf_token" => "B6waDcMoAdKS0i7arAxuhW9p"}

**Comment by Zurga** [comment]
Thank you for the very detailed bug report! 
I have fixed this issue in some un-pushed code and will push now :)
