### ISSUE TITLE
Putting the CDN inside a layout_view.ex not compile

### ISSUE THREAD

**Issue by romenigld** [surface-ui/surface_bulma#4]
I was trying to use bulma's CSS styles sing CDN and when I try to put inside the `layout_view.ex`.
The phoenix not compile.
I installed doing by:
` npm install --save-dev bulma`
and adding on the `app.scss`:
`@import 'bulma';`

**Comment by olivermt** [comment]
Do you mean added to layout template? 
Could you show the compile error?

**Comment by romenigld** [comment]
sorry I don't have the error now.
But [here](http://surface-demo.msaraiva.io/uicomponents) tells to put on the `layout_view.ex` file.

**Comment by olivermt** [comment]
Hey!

That is a typo, it should go in your root or app template (you'll find similar stylesheet and js links in there so you know you're in the right file).

**Comment by olivermt** [comment]
You should probably update this @msaraiva until we publish the proper catalogue as a replacement for surface_site.

This should both say ´root.html.leex´ :)

**Comment by olivermt** [comment]
This was supposed to be this screenshot:
![image](https://user-images.githubusercontent.com/737765/106948618-3926d400-672c-11eb-9437-db0d4b97575d.png)

**Comment by msaraiva** [comment]
Closing this in favour of https://github.com/surface-ui/surface_site/issues/4
